apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirest-nest
  namespace: genericappnamespace
  labels:
    app: apirest-nest
spec:
  selector:
    matchLabels:
      app: apirest-nest
  replicas: 1
  template:
    metadata:
      labels:
        app: apirest-nest
        env: development
    spec:
      containers:
        - name: apirest-nest
          image: gcr.io/[PROJECT_ID]/app:v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: LOG_LEVEL
              value: 'info'
            - name: NODE_ENV
              value: 'development'
---
apiVersion: v1
kind: Service
metadata:
  name: apirest-nest
  namespace: genericappnamespace
  labels:
    app: apirest-nest
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-app
