apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: apirest-nest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apirest-nest
  template:
    metadata:
      labels:
        app: apirest-nest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: backend-nestjs
          image: 132970462391.dkr.ecr.us-east-2.amazonaws.com/backend-nestjs:latest
          ports:
            - containerPort: 8080
